services:

  first:
    restart: always
    container_name: first
    build:
      context: ./first
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - api.insecure=true
      - traefik.http.services.app.loadbalancer.server.port=8081
      - traefik.http.routers.first.entrypoints=http
      - traefik.http.routers.first.rule=Host(`one.localhost`)
      - traefik.docker.network=twoapp
    command: [ "node", "app.js" ]
    networks:
      - twoapp

  second:
    restart: always
    container_name: second
    build:
      context: ./second
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - api.insecure=true
      - traefik.http.services.app.loadbalancer.server.port=8082
      - traefik.http.routers.second.entrypoints=http
      - traefik.http.routers.second.rule=Host(`two.localhost`)

      - traefik.docker.network=twoapp
    command: [ "node", "server.js" ]
    networks:
      - twoapp

networks:
  twoapp:
    external: true
